#!/usr/bin/python

from datetime import datetime
from dateutil.relativedelta import *
from random import randrange
from sys import argv

DAY_NAMES = ["first",
             "second",
             "third",
             "fourth",
             "fifth",
             "sixth",
             "seventh",
             "eighth",
             "ninth",
             "tenth",
             "eleventh",
             "twelfth",
             "thirteenth",
             "fourteenth",
             "fifteenth",
             "sixteenth",
             "seventeenth",
             "eighteenth",
             "nineteenth",
             "twentieth",
             "twenty first",
             "twenty second",
             "twenty third",
             "twenty fourth",
             "twenty fifth",
             "twenty sixth",
             "twenty seventh",
             "twenty eighth",
             "twenty ninth",
             "thirtieth",
             "thirty first"]
 
MONTH_NAMES = ["january",
               "february",
               "march",
               "april",
               "may",
               "june",
               "july",
               "august",
               "september",
               "october",
               "november",
               "december"]

now = datetime.now()
seen = []
first = int(argv[3])
last = int(argv[4])
cnt = min(int(argv[2]), last - first)
while len(seen) < cnt:
    delta = randrange(first, last)
    if delta not in seen:
        seen.append(delta)
        if argv[1] == "day":
            print(DAY_NAMES[(now + relativedelta(days=delta)).day - 1])
        elif argv[1] == "month":
            print(MONTH_NAMES[(now + relativedelta(months=delta)).month - 1])

